Following:
http://scipy-cookbook.readthedocs.io/items/LoktaVolterraTutorial.html

In [1]:
from numpy import *
#import pylab as p
import matplotlib as plt
# Definition of parameters
import math
a = math.log(2)
b = math.log(2)/5
c = math.log(2)/20
d = math.log(2)
def dX_dt(X, t=0):
    """ Return the growth rate of fox and rabbit populations. """
    return array([ a*X[0] -   b*X[0]*X[1] ,
                  -c*X[1] + d*b*X[0]*X[1] ])

In [2]:
#find fixed points

X_f0 = array([     0. ,  0.])
X_f1 = array([ c/(d*b), a/b])
all(dX_dt(X_f0) == zeros(2) ) and all(dX_dt(X_f1) == zeros(2)) # => True

False

In [3]:
def d2X_dt2(X, t=0):
    """ Return the Jacobian matrix evaluated in X. """
    return array([[a -b*X[1],   -b*X[0]     ],
                  [b*d*X[1] ,   -c +b*d*X[0]] ])

In [4]:
A_f0 = d2X_dt2(X_f0) 

In [5]:
A_f0

array([[ 0.69314718, -0.        ],
       [ 0.        , -0.03465736]])

In [6]:
A_f1 = d2X_dt2(X_f1)

In [7]:
A_f0

array([[ 0.69314718, -0.        ],
       [ 0.        , -0.03465736]])

In [8]:
X_f1

array([ 0.36067376,  5.        ])